[package]
name = "signage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svm-rs-builds = { version = "0.1.11", features = ["_offline"] }
